# Generated by Django 5.2.1 on 2025-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task', 'Задача'), ('test', 'Контрольная работа'), ('course', 'Курсовая работа')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateField()),
                ('file', models.FileField(blank=True, upload_to='orders/')),
            ],
        ),
    ]
