# Generated by Django 5.2.1 on 2025-05-23 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_subject_created_at_alter_subject_name_and_more'),
        ('orders', '0003_order_payed_dispute_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='order',
            name='complexity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.complexity', verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок сдачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_orders', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('revision', 'На доработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='order',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.worktype', verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Комментарий к заказу',
                'verbose_name_plural': 'Комментарии к заказу',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('task', 'Задание'), ('solution', 'Решение'), ('revision', 'Доработка')], max_length=20, verbose_name='Тип файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order', verbose_name='Заказ')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл заказа',
                'verbose_name_plural': 'Файлы заказа',
                'ordering': ['-created_at'],
            },
        ),
    ]
