# Generated by Django 5.2.1 on 2025-05-23 09:59

import apps.orders.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_remove_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to=apps.orders.utils.get_file_path, validators=[apps.orders.utils.FileValidator()], verbose_name='Файл'),
        ),
    ]
