# Generated by Django 5.2.1 on 2025-05-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_discountrule'),
        ('orders', '0005_orderfile_description_alter_orderfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_requirements',
            field=models.JSONField(blank=True, help_text='Дополнительные требования к заказу (уникальность, форматирование и т.д.)', null=True, verbose_name='Дополнительные требования'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.discountrule', verbose_name='Примененная скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Изначальная цена'),
        ),
    ]
