# Generated by Django 5.2.1 on 2025-07-12 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_discountrule'),
        ('orders', '0006_order_additional_requirements_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complexity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.complexity', verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('waiting_payment', 'Ожидает оплаты'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('revision', 'На доработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.worktype', verbose_name='Тип работы'),
        ),
    ]
