# Generated by Django 5.2.1 on 2025-09-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_complexity_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Произвольная тема'),
        ),
    ]
