# Generated by Django 5.2.1 on 2025-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('expert', 'Expert'), ('arbitrator', 'Arbitrator'), ('admin', 'Admin'), ('franchisee', 'Franchisee')], default='client', max_length=20),
        ),
    ]
