# Generated by Django 5.2.1 on 2025-09-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Почасовая ставка'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки'),
        ),
    ]
