# Generated by Django 5.2.1 on 2025-10-02 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_bid'),
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='franchisee',
        ),
        migrations.AddField(
            model_name='user',
            name='active_referrals',
            field=models.PositiveIntegerField(default=0, verbose_name='Активных рефералов'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Процент партнера (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий доход'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего рефералов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('expert', 'Expert'), ('arbitrator', 'Arbitrator'), ('admin', 'Admin'), ('partner', 'Partner')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='PartnerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма начисления')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент комиссии')),
                ('source_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Исходная сумма')),
                ('earning_type', models.CharField(choices=[('order', 'Заказ'), ('registration', 'Регистрация'), ('bonus', 'Бонус')], default='order', max_length=20, verbose_name='Тип начисления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Выплачено')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_earnings', to=settings.AUTH_USER_MODEL, verbose_name='Реферал')),
            ],
            options={
                'verbose_name': 'Доход партнера',
                'verbose_name_plural': 'Доходы партнеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
