# Generated by Django 5.2.1 on 2025-05-23 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0003_order_payed_dispute_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('document_type', models.CharField(choices=[('diploma', 'Диплом'), ('certificate', 'Сертификат'), ('award', 'Награда'), ('other', 'Другое')], max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='expert_docs/', verbose_name='Файл')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
            ],
            options={
                'verbose_name': 'Документ эксперта',
                'verbose_name_plural': 'Документы экспертов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('expert', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт (лет)')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('description', models.TextField(blank=True, verbose_name='Описание опыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='catalog.subject', verbose_name='Предмет')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_specializations', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['-verified', '-experience'],
                'unique_together': {('expert', 'subject')},
            },
        ),
    ]
