# Generated by Django 5.2.1 on 2025-05-23 09:59

import apps.orders.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        ('orders', '0005_orderfile_description_alter_orderfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв об эксперте', 'verbose_name_plural': 'Отзывы об экспертах'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['-is_verified', '-experience_years'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.RenameField(
            model_name='expertdocument',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='specialization',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='expertdocument',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='expertreview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='expertreview',
            name='text',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='expertdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часовая ставка'),
        ),
        migrations.AlterField(
            model_name='expertdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),
        ),
        migrations.AlterField(
            model_name='expertdocument',
            name='document_type',
            field=models.CharField(choices=[('diploma', 'Диплом'), ('certificate', 'Сертификат'), ('award', 'Награда'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='expertdocument',
            name='file',
            field=models.FileField(upload_to='experts/documents/', validators=[apps.orders.utils.FileValidator()], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='expertdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expertdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_review', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.CreateModel(
            name='ExpertStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_completed', models.PositiveIntegerField(default=0, verbose_name='Выполнено заказов')),
                ('orders_in_progress', models.PositiveIntegerField(default=0, verbose_name='Заказов в работе')),
                ('orders_cancelled', models.PositiveIntegerField(default=0, verbose_name='Отмененных заказов')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий заработок')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент успешных заказов')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Статистика эксперта',
                'verbose_name_plural': 'Статистика экспертов',
            },
        ),
    ]
