# Generated by Django 5.2.1 on 2025-05-23 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_cleanup_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertdocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружен'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='expertstatistics',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
    ]
