# Generated by Django 5.2.1 on 2025-05-23 12:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_cleanup_and_make_client_required'),
        ('orders', '0005_orderfile_description_alter_orderfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertstatistics',
            name='orders_cancelled',
        ),
        migrations.RemoveField(
            model_name='expertstatistics',
            name='orders_completed',
        ),
        migrations.RemoveField(
            model_name='expertstatistics',
            name='orders_in_progress',
        ),
        migrations.AddField(
            model_name='expertstatistics',
            name='completed_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполненные заказы'),
        ),
        migrations.AddField(
            model_name='expertstatistics',
            name='response_time_avg',
            field=models.DurationField(blank=True, null=True, verbose_name='Среднее время ответа'),
        ),
        migrations.AddField(
            model_name='expertstatistics',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего заказов'),
        ),
        migrations.AlterField(
            model_name='expertstatistics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.CreateModel(
            name='ExpertRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_rating', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Рейтинг эксперта',
                'verbose_name_plural': 'Рейтинги экспертов',
                'ordering': ['-created_at'],
                'unique_together': {('expert', 'order')},
            },
        ),
    ]
