# Generated by Django 5.2.1 on 2025-05-23 12:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_subject_options_alter_subjectcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percentage', max_length=20, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение скидки')),
                ('min_orders', models.PositiveIntegerField(default=0, help_text='Минимальное количество выполненных заказов для получения скидки', verbose_name='Минимальное количество заказов')),
                ('min_total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Минимальная общая сумма выполненных заказов для получения скидки', max_digits=10, verbose_name='Минимальная сумма заказов')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('work_types', models.ManyToManyField(blank=True, help_text='Оставьте пустым для применения ко всем типам работ', to='catalog.worktype', verbose_name='Типы работ')),
            ],
            options={
                'verbose_name': 'Правило скидки',
                'verbose_name_plural': 'Правила скидок',
                'ordering': ['-value', 'min_orders', 'min_total_spent'],
            },
        ),
    ]
