# Generated by Django 5.2.1 on 2025-09-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_discountrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
