# Generated by Django 5.2.1 on 2025-05-23 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_order', 'Новый заказ'), ('order_taken', 'Заказ принят'), ('file_uploaded', 'Загружен файл'), ('new_comment', 'Новый комментарий'), ('status_changed', 'Изменен статус'), ('deadline_soon', 'Скоро дедлайн'), ('document_verified', 'Документ проверен'), ('specialization_verified', 'Специализация подтверждена'), ('review_received', 'Получен отзыв'), ('payment_received', 'Получена оплата'), ('order_completed', 'Заказ завершен'), ('new_contact', 'Новое обращение')], max_length=30, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип связанного объекта')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['type', 'is_read'], name='notificatio_type_5ae648_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'), models.Index(fields=['is_read', 'created_at'], name='notificatio_is_read_3a06ff_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_f82ec2_idx')],
            },
        ),
    ]
