# Generated by Django 5.2.1 on 2025-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'Новый заказ'), ('order_taken', 'Заказ принят'), ('file_uploaded', 'Загружен файл'), ('new_comment', 'Новый комментарий'), ('status_changed', 'Изменен статус'), ('deadline_soon', 'Скоро дедлайн'), ('document_verified', 'Документ проверен'), ('specialization_verified', 'Специализация подтверждена'), ('review_received', 'Получен отзыв'), ('new_rating', 'Новый рейтинг'), ('rating_milestone', 'Достижение рейтинга'), ('payment_received', 'Получена оплата'), ('order_completed', 'Заказ завершен'), ('new_contact', 'Новое обращение')], max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
